export interface BlogPost {
  id: number;
  title: string;
  excerpt: string;
  content: string[];
  author: string;
  date: string;
  readTime: string;
  category: string;
  image: string;
  featured?: boolean;
}

export const categories = [
  { id: 'all', name: 'All' },
  { id: 'fashion', name: 'Fashion' },
  { id: 'interiors', name: 'Interiors' },
  { id: 'lifestyle', name: 'Lifestyle' },
  { id: 'design', name: 'Design' },
  { id: 'gala', name: 'Gala' },
];

export const featuredPost: BlogPost = {
  id: 1,
  title: 'The Art of Minimalist Luxury: Redefining Elegance in Modern Design',
  excerpt: 'Discover how minimalist principles can elevate luxury design, creating spaces and wardrobes that speak volumes through restraint and intentionality. From curated capsule wardrobes to serene interiors that breathe, learn how less can truly mean more when every element is chosen with purpose and refined aesthetic vision.',
  content: [
    'In a world of excess, minimalist luxury stands apart. It\'s not about having less for the sake of it—it\'s about having exactly what matters, curated with intention and refined aesthetic vision.',
    'From curated capsule wardrobes that mix and match effortlessly to serene interiors that breathe, minimalist principles can elevate both fashion and design. Every element earns its place; nothing is superfluous.',
    'The key is restraint. When you remove the noise, what remains speaks volumes. A single statement piece, a perfectly placed vase, a well-tailored coat—each carries more weight when it has room to be seen.',
    'Dr. Bea Foster has spent decades teaching that luxury is not measured by quantity but by quality and intention. Whether designing a room or an outfit, the same principles apply: choose wisely, edit fiercely, and let each piece tell its story.',
    'Embrace the art of less. Your spaces and wardrobe will thank you.',
  ],
  author: 'The Black Tie Chandelier Gala',
  date: 'March 15, 2024',
  readTime: '8 min read',
  category: 'design',
  image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&q=80',
  featured: true,
};

export const blogPosts: BlogPost[] = [
  {
    id: 2,
    title: 'Spring 2024 Fashion Trends: What to Expect',
    excerpt: 'A comprehensive guide to the upcoming spring fashion trends, from color palettes to silhouettes that will define the season. We explore flowing fabrics, soft neutrals, and statement accessories that will help you step into spring with confidence and elegance.',
    author: 'The Black Tie Chandelier Gala',
    date: 'March 10, 2024',
    readTime: '5 min read',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80',
    content: [
      'Spring brings a fresh palette and new silhouettes that define the season. This year, we\'re seeing a beautiful blend of flowing fabrics, soft neutrals, and bold statement accessories.',
      'Soft pastels—blush pink, sky blue, mint green—continue to dominate, while earthy neutrals like sand and cream provide a timeless foundation. The key is layering: light knits over silk blouses, tailored blazers over flowy dresses.',
      'Silhouettes are leaning toward relaxed, effortless shapes. Wide-leg trousers, midi skirts, and oversized blazers create movement and grace. Accessories make the outfit: sculptural earrings, woven bags, and delicate gold chains.',
      'At The Black Tie Chandelier Gala, we believe in investing in pieces that transcend trends. Choose items that feel like you—elegant, intentional, and ready for whatever the season brings.',
    ],
  },
  {
    id: 3,
    title: 'Transforming Small Spaces: Interior Design Secrets',
    author: 'The Black Tie Chandelier Gala',
    date: 'March 5, 2024',
    readTime: '6 min read',
    category: 'interiors',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80',
    excerpt: 'Learn how to maximize style and functionality in compact living spaces with these expert interior design techniques. Discover clever storage solutions, strategic lighting, and multi-functional furniture that transform cramped rooms into sophisticated sanctuaries.',
    content: [
      'Small spaces demand creativity—and the right approach can turn limitations into advantages. With strategic design choices, compact rooms become cozy, functional, and distinctly luxurious.',
      'Start with storage. Built-ins, under-bed drawers, and multi-functional furniture hide clutter while adding style. Mirrors expand visual space; strategic lighting creates depth and ambiance.',
      'Choose a cohesive color palette to unify the room. Lighter tones open up the space, while one accent color adds personality. Scale matters: smaller furniture and fewer pieces prevent overwhelm.',
      'Dr. Bea Foster has transformed countless small spaces throughout her career. Her secret? Edit ruthlessly, invest in quality pieces that serve multiple purposes, and never sacrifice elegance for square footage.',
    ],
  },
  {
    id: 4,
    title: 'The Psychology of Color in Luxury Design',
    author: 'The Black Tie Chandelier Gala',
    date: 'February 28, 2024',
    readTime: '7 min read',
    category: 'design',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80',
    excerpt: 'Explore how color choices impact mood, perception, and the overall luxury experience in both fashion and interior design. From the calming influence of soft blues to the power of deep blacks, understand the emotional language of color in high-end aesthetics.',
    content: [
      'Color speaks a language all its own. In luxury design—whether fashion or interiors—the hues we choose communicate mood, evoke emotion, and shape how we experience a space or an outfit.',
      'Deep blacks and rich charcoals convey power and sophistication. Gold accents add warmth and opulence. Soft blues and greens create calm; creams and whites offer clarity and light.',
      'The key is intentionality. Every color in a room or outfit should earn its place. Complement your skin tone, your space\'s light, and the mood you want to create.',
      'At The Black Tie Chandelier Gala, our signature palette—black, white, cream, and gold—reflects timeless elegance. These colors never go out of style and work in every context.',
    ],
  },
  {
    id: 5,
    title: 'Sustainable Luxury: The Future of Fashion',
    author: 'The Black Tie Chandelier Gala',
    date: 'February 20, 2024',
    readTime: '9 min read',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80',
    excerpt: 'How the luxury fashion industry is embracing sustainability without compromising on elegance and quality. Discover ethical sourcing, timeless designs that last decades, and brands leading the way toward a more conscious approach to luxury.',
    content: [
      'Luxury and sustainability are no longer at odds. Today\'s discerning consumers expect both—elegance and ethics, quality and conscience.',
      'Ethical sourcing, recycled materials, and timeless designs that last decades are becoming the standard. Brands that invest in craftsmanship over fast fashion are leading the way.',
      'The most sustainable piece is one you\'ll wear for years. Invest in quality fabrics, classic cuts, and pieces that transcend seasons. Care for your wardrobe—repair, rewear, and pass down.',
      'The Black Tie Chandelier Gala celebrates conscious luxury. From our B. Sporty collection to our design philosophy, we believe in creating pieces that last and choices that matter.',
    ],
  },
  {
    id: 6,
    title: 'Creating Your Dream Home: A Step-by-Step Guide',
    author: 'The Black Tie Chandelier Gala',
    date: 'February 15, 2024',
    readTime: '10 min read',
    category: 'interiors',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    excerpt: 'From concept to completion, discover the essential steps to creating a home that reflects your personal style and luxury aspirations. We walk through consultation, mood boards, material selection, and the finishing touches that make a space truly yours.',
    content: [
      'Creating your dream home is a journey—one that begins with a vision and ends with a space that feels uniquely yours. Here\'s how to approach it with intention.',
      'Start with a consultation. Define your style, your needs, and your budget. Mood boards help crystallize your vision before any work begins.',
      'Material selection matters. From fabrics to finishes, every choice contributes to the final result. Don\'t rush—take time to touch, see, and imagine each element in your space.',
      'The finishing touches—art, accessories, lighting—bring it all together. Dr. Bea Foster has spent decades perfecting this process. Her advice: trust the process, stay true to your vision, and enjoy the transformation.',
    ],
  },
  {
    id: 7,
    title: 'The Art of Entertaining: Hosting with Style',
    author: 'The Black Tie Chandelier Gala',
    date: 'February 10, 2024',
    readTime: '6 min read',
    category: 'lifestyle',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    excerpt: 'Master the art of hosting elegant gatherings with tips on table settings, ambiance, and creating memorable experiences. From intimate dinners to grand celebrations, learn how to welcome guests with grace and leave them feeling cherished.',
    content: [
      'Hosting is an art—one that combines preparation, presence, and a genuine desire to make others feel seen and celebrated.',
      'Table settings set the tone. Invest in quality linens, meaningful china, and thoughtful centerpieces. Lighting matters: dim, warm, and flattering creates the right mood.',
      'The best hosts anticipate needs without hovering. A well-stocked bar, comfortable seating, and a relaxed attitude put guests at ease.',
      'At The Black Tie Chandelier Gala, we believe every gathering is an opportunity to elevate and connect. Whether intimate or grand, the goal is the same: make your guests feel cherished.',
    ],
  },
  {
    id: 8,
    title: 'Couture vs. Ready-to-Wear: Understanding the Difference',
    author: 'The Black Tie Chandelier Gala',
    date: 'February 5, 2024',
    readTime: '8 min read',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80',
    excerpt: 'Dive deep into the world of haute couture and understand what sets it apart from ready-to-wear fashion. From hand-sewn craftsmanship to bespoke fittings, discover why couture represents the pinnacle of sartorial excellence.',
    content: [
      'Haute couture represents the pinnacle of fashion—handcrafted, bespoke, and made to measure. Ready-to-wear offers accessibility and style at a different scale. Both have their place.',
      'Couture garments are created by hand, fitted to the individual, and often require hundreds of hours of work. Every seam, bead, and button is placed with precision.',
      'Ready-to-wear brings designer vision to a wider audience. Quality varies—invest in brands that prioritize craftsmanship, fabric, and cut.',
      'Dr. Bea Foster has worked in both worlds. Her advice: know the difference, invest where it matters, and always choose pieces that make you feel extraordinary.',
    ],
  },
  {
    id: 9,
    title: 'Maximalist Interiors: When More is More',
    author: 'The Black Tie Chandelier Gala',
    date: 'January 30, 2024',
    readTime: '7 min read',
    category: 'interiors',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    excerpt: 'Explore the bold world of maximalist interior design and learn how to create rich, layered spaces with confidence. Layer patterns, mix textures, and embrace bold colors to create interiors that tell your unique story.',
    content: [
      'Maximalism is not chaos—it\'s curated abundance. When done right, bold patterns, rich textures, and layered accents create spaces that feel alive and uniquely yours.',
      'The key is cohesion. Choose a color family or theme that ties everything together. Mix patterns in complementary scales—large florals with small geometrics, stripes with paisleys.',
      'Texture adds depth. Velvet, silk, linen, leather—layering materials creates sensory richness. Don\'t be afraid of bold art, statement lighting, or eclectic collections.',
      'At The Black Tie Chandelier Gala, we celebrate individuality. Whether minimalist or maximalist, the goal is a space that reflects who you are.',
    ],
  },
  {
    id: 10,
    title: 'Building a Timeless Wardrobe: Investment Pieces',
    author: 'The Black Tie Chandelier Gala',
    date: 'January 25, 2024',
    readTime: '5 min read',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80',
    excerpt: 'Learn which pieces deserve investment and how to build a wardrobe that transcends trends and seasons. From the perfect blazer to quality leather accessories, discover the foundations of a closet that works for years.',
    content: [
      'A timeless wardrobe is built on foundations—pieces that never go out of style and work across seasons and occasions.',
      'Start with a tailored blazer, a crisp white shirt, well-fitted trousers, and a little black dress. Add quality leather accessories: a handbag, a belt, and versatile shoes.',
      'Neutral colors—black, white, navy, camel—mix and match effortlessly. Invest in quality fabrics: wool, silk, cashmere. They last longer and look better.',
      'Dr. Bea Foster\'s philosophy: buy less, choose well. A closet of intentional pieces beats a closet of trends every time.',
    ],
  },
  {
    id: 11,
    title: 'The Black Tie Chandelier Gala: A Night of Elegance and Purpose',
    author: 'The Black Tie Chandelier Gala',
    date: 'January 20, 2024',
    readTime: '6 min read',
    category: 'gala',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80',
    excerpt: 'Behind the scenes of our signature gala event—where fashion, philanthropy, and community come together. Learn about our mission to honor loved ones, support cancer research, and create unforgettable experiences that elevate and inspire.',
    content: [
      'The Black Tie Chandelier Gala is more than an event—it\'s a movement. Born from love and loss, it exists to honor those we\'ve lost, support cancer research, and create moments of beauty and connection.',
      'Each year, we bring together a community of supporters, designers, and dreamers for an evening of elegance, entertainment, and purpose. The runway, the music, the atmosphere—all designed to elevate and inspire.',
      'Proceeds support cancer research and families affected by the disease. Every ticket, every sponsor, every donation contributes to a future we believe in.',
      'Join us. Dress up. Show up. Be part of something beautiful.',
    ],
  },
  {
    id: 12,
    title: 'What to Wear: Your Black Tie Gala Style Guide',
    author: 'The Black Tie Chandelier Gala',
    date: 'January 15, 2024',
    readTime: '5 min read',
    category: 'gala',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    excerpt: 'From floor-length gowns to tailored tuxedos, master the art of black-tie dressing for our annual gala. Discover color choices, fabric considerations, and accessories that ensure you look and feel your absolute best on this special night.',
    content: [
      'Black tie calls for your best. For women: floor-length gowns or elegant cocktail dresses. For men: tuxedos or dark suits with bow ties. The goal is polished, elegant, and memorable.',
      'Color choices matter. Classic black and navy never fail. Jewel tones—emerald, sapphire, ruby—make a statement. Metallics add glamour for those who dare.',
      'Fabric and fit are everything. Choose materials that move and drape well. Tailoring makes the difference—invest in alterations for a perfect fit.',
      'Accessories complete the look. Statement jewelry, a clutch, elegant heels. For men: cufflinks, a pocket square, polished shoes. You\'re not just dressing—you\'re presenting your best self.',
    ],
  },
  {
    id: 13,
    title: 'Proportion and Balance: The Foundation of Great Design',
    author: 'The Black Tie Chandelier Gala',
    date: 'January 10, 2024',
    readTime: '7 min read',
    category: 'design',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80',
    excerpt: 'Whether designing a room or an outfit, proportion and balance are the invisible forces that make everything feel right. Explore how scale, symmetry, and rhythm create harmony in both interiors and fashion.',
    content: [
      'Proportion and balance are the invisible forces that make design feel right. When they\'re off, something feels wrong—even if we can\'t always name it.',
      'Scale matters. Oversized furniture in a small room overwhelms; tiny accessories on a bold outfit get lost. Match the size of elements to the space or body they inhabit.',
      'Symmetry creates calm; asymmetry adds interest. Use both intentionally. Rhythm—repeating elements at intervals—creates flow and cohesion.',
      'Dr. Bea Foster teaches proportion in every design class. Her rule: trust your eye, but learn the principles. Great design feels effortless because the math is right.',
    ],
  },
  {
    id: 14,
    title: 'Textures in Luxury: From Velvet to Silk',
    author: 'The Black Tie Chandelier Gala',
    date: 'January 5, 2024',
    readTime: '6 min read',
    category: 'design',
    image: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=80',
    excerpt: 'Texture adds depth and tactile pleasure to any design. Discover how to layer fabrics, mix materials, and create sensory richness in your wardrobe and home. Velvet, silk, cashmere, and linen—each tells a different story.',
    content: [
      'Texture is the secret ingredient of luxury. It\'s what we touch, what we feel—the difference between flat and rich, cold and inviting.',
      'Velvet conveys opulence. Silk adds sheen and softness. Cashmere brings warmth. Linen offers crisp, relaxed elegance. Each has its place and its season.',
      'In interiors, layering textures—a wool throw on a leather chair, silk pillows on a linen sofa—creates depth. In fashion, mixing materials adds dimension to an outfit.',
      'The Black Tie Chandelier Gala celebrates texture in all its forms. From our fashion line to our design work, we believe in pieces that feel as good as they look.',
    ],
  },
  {
    id: 15,
    title: 'Accessorizing for Impact: The Finishing Touches',
    author: 'The Black Tie Chandelier Gala',
    date: 'December 28, 2023',
    readTime: '5 min read',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1594221708779-94832f4320d1?w=800&q=80',
    excerpt: 'The right accessories can elevate any outfit from good to unforgettable. Explore statement jewelry, elegant scarves, and handbag choices that complement your personal style and complete your look with intention.',
    content: [
      'Accessories are the finishing touches that transform an outfit from good to unforgettable. They\'re where personality meets polish.',
      'Statement jewelry—bold earrings, a striking necklace—can make a simple outfit memorable. Choose pieces that complement your neckline and frame your face.',
      'Scarves add color, texture, and versatility. A silk scarf can be worn dozens of ways. Handbags should be proportional to your frame and purposeful for the occasion.',
      'Less is often more—one or two strong pieces beat a jumble of trends. Dr. Bea Foster advises: choose accessories that feel like you and wear them with confidence.',
    ],
  },
  {
    id: 16,
    title: 'Dressing for Your Body: Flattering Silhouettes',
    author: 'The Black Tie Chandelier Gala',
    date: 'December 22, 2023',
    readTime: '6 min read',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80',
    excerpt: 'Learn how to choose silhouettes that celebrate your unique shape. From A-line to tailored fits, discover the cuts and styles that flatter and empower, helping you feel confident in every occasion.',
    content: [
      'The best-dressed people don\'t follow trends—they honor their bodies. Knowing your shape and what flatters it is the foundation of personal style.',
      'A-line silhouettes suit many body types, offering structure without rigidity. Tailored fits create clean lines. Wrap styles emphasize the waist. High-waisted trousers lengthen the leg.',
      'Fabric and fit matter as much as silhouette. Stiff fabrics add structure; flowing fabrics soften. The right fit—not too tight, not too loose—makes all the difference.',
      'At The Black Tie Chandelier Gala, we believe everyone deserves to feel beautiful. Find what works for you and wear it with pride.',
    ],
  },
  {
    id: 17,
    title: 'Lighting Your Space: Ambient, Task, and Accent',
    author: 'The Black Tie Chandelier Gala',
    date: 'December 18, 2023',
    readTime: '7 min read',
    category: 'interiors',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80',
    excerpt: 'Lighting transforms a room more than any other single element. Master the three layers—ambient, task, and accent—to create atmospheres that are both functional and breathtaking. From chandeliers to sconces.',
    content: [
      'Lighting transforms a room more than any other single element. Get it right, and your space comes alive. Get it wrong, and even beautiful furniture falls flat.',
      'Ambient lighting provides overall illumination—overhead fixtures, recessed lights. Task lighting targets specific areas—desk lamps, under-cabinet lights. Accent lighting highlights—sconces, spotlights on art.',
      'Layer all three for depth and flexibility. Dimmer switches let you adjust mood. Warm bulbs (2700K–3000K) create coziness; cooler bulbs (3500K+) suit work spaces.',
      'The Black Tie Chandelier Gala takes its name from lighting—the chandelier as a symbol of elegance and illumination. Let light elevate your space.',
    ],
  },
  {
    id: 18,
    title: 'Window Treatments: Drapery That Dazzles',
    author: 'The Black Tie Chandelier Gala',
    date: 'December 12, 2023',
    readTime: '8 min read',
    category: 'interiors',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
    excerpt: 'Often called "the Queen of Swags," Dr. Bea shares her expertise on window treatments. From custom drapery to roman shades, learn how the right window dressing can frame your views and elevate any room.',
    content: [
      'Window treatments are often overlooked—but they\'re one of the most impactful elements in a room. They frame views, control light, and add texture and color.',
      'Dr. Bea Foster earned the title "Queen of Swags" for her exquisite drapery work. Custom drapery, roman shades, and valances can transform a room from plain to polished.',
      'Fabric choice matters. Heavy fabrics block light and add drama; sheer fabrics soften and filter. Hardware—rods, finials—should complement the overall design.',
      'Invest in quality window treatments. They last decades and significantly affect how a space feels. It\'s one of the best returns on design investment.',
    ],
  },
  {
    id: 19,
    title: 'Morning Rituals: Starting Your Day with Intention',
    author: 'The Black Tie Chandelier Gala',
    date: 'December 8, 2023',
    readTime: '5 min read',
    category: 'lifestyle',
    image: 'https://images.unsplash.com/photo-1490814525860-594e82bfd34b?w=800&q=80',
    excerpt: 'How you begin your day sets the tone for everything that follows. Discover simple rituals—from skincare to a curated morning soundtrack—that help you step into each day with grace and purpose.',
    content: [
      'How you begin your day sets the tone for everything that follows. Intentional morning rituals—no matter how small—create a foundation of calm and purpose.',
      'Skincare is self-care. A gentle cleanse, moisturizer, and sunscreen take minutes but pay dividends. Create a routine that feels luxurious, not rushed.',
      'Move your body. Stretch, walk, or practice a few moments of mindfulness. Physical ritual grounds the mind.',
      'The Black Tie Chandelier Gala believes in living with intention. Start your day with grace, and carry that energy forward.',
    ],
  },
  {
    id: 20,
    title: 'Gift-Giving with Heart: Thoughtful Luxury',
    author: 'The Black Tie Chandelier Gala',
    date: 'December 2, 2023',
    readTime: '6 min read',
    category: 'lifestyle',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&q=80',
    excerpt: 'The art of giving goes beyond the price tag. Learn how to choose gifts that reflect thoughtfulness, align with the recipient\'s style, and create lasting memories. From hostess gifts to milestone celebrations.',
    content: [
      'The best gifts reflect thoughtfulness—not just budget. Consider the recipient\'s tastes, their life, their story. A meaningful gift says, "I see you."',
      'For hostess gifts: beautiful candles, quality olive oil, or a small bouquet. For milestones: something they\'ll use and remember. For everyday: a note, a coffee, a moment of presence.',
      'Presentation matters. Wrap with care. Add a handwritten note. The extra effort communicates respect and love.',
      'At The Black Tie Chandelier Gala, we believe in gifts that elevate—whether a B. Sporty item, a design consultation, or simply the gift of your presence and attention.',
    ],
  },
];

export const allPosts: BlogPost[] = [featuredPost, ...blogPosts];

export function getPostById(id: number | string): BlogPost | undefined {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  return allPosts.find(post => post.id === numId);
}
